platform :ios, '8.0'
use_frameworks!

target 'Mikoto_Example' do
  pod 'Mikoto', :path => '../'
  pod 'Mikoto/Encrypt', :path => '../'

  target 'Mikoto_Tests' do
    inherit! :search_paths

    
  end
end
