# https://docs.fastlane.tools/actions
# fastlane release ver:0.1.0
lane :release do |ops|
  ver = ops[:ver]
  raise "ver is missed." if ver.nil?
  cocoapods(clean: true, podfile: "./Example/Podfile")
  git_commit(path: ".", message: "update")
  add_git_tag(tag: "v#{ver}")
  push_to_git_remote
  push_to_git_remote(remote_branch: ver)
  pod_lib_lint
  pod_push
end
